lib/tartu_smarter_bike_web/router.ex
defmodule TartuSmarterBikeWeb.Router do
  use TartuSmarterBikeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TartuSmarterBikeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug TartuSmarterBike.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end



  scope "/", TartuSmarterBikeWeb do
    pipe_through [:browser]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", TartuSmarterBikeWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
    get "/account", PageController, :home
    get "/invoice", PageController, :invoice
    get "/membership_form", PageController, :membership_form
    post "/membership", PageController, :membership
    get "/prepaid_form", PageController, :prepaid_form
    post "/prepaid", PageController, :prepaid
    get "/gifting_form", PageController, :gifting_form
    post "/gifting", PageController, :gifting
    get "/map", PageController, :map
    post "/rides/report", RideController, :report
    post "/rides/unlock", RideController, :unlock
    post "/rides/book", RideController, :book
    get "/rides/report_form", RideController, :report_form
    post "/rides/arrived", RideController, :arrived
    get "/rides/arrived_form", RideController, :arrived_form
    get "/rides/complete", RideController, :complete_ride
    get "/rides/rankings", RideController, :ranking
    resources "/users", UserController
    resources "/rides", RideController

  end

  # Other scopes may use custom stacks.
  # scope "/api", TartuSmarterBikeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TartuSmarterBikeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/tartu_smarter_bike_web/views/layout_view.ex
defmodule TartuSmarterBikeWeb.LayoutView do
  use TartuSmarterBikeWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/tartu_smarter_bike_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/tartu_smarter_bike_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/tartu_smarter_bike_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Tartu Smarter Bike", suffix: "" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.24.0/axios.min.js" integrity="sha512-u9akINsQsAkG9xjc1cnGF4zw5TFDwkxuc9vUp5dltDWYCSmyd0meygbvgXrlc/z7/o4a19Fb5V0OUE58J7dcyw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://kit.fontawesome.com/70f86e07f8.js" crossorigin="anonymous"></script>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>

  </head>
  <body>
    <header>
      <nav>
        <span>
          <%= link "Home", to: Routes.page_path(@conn, :index) %>
          <%= link "Rankings", to: Routes.ride_path(@conn, :ranking) %>
          <%= if TartuSmarterBike.Authentication.load_current_user(@conn) do %>
            <%= link "Map", to: Routes.page_path(@conn, :map) %>            
          <% end %>
        </span>
        <span>
          <%= if TartuSmarterBike.Authentication.load_current_user(@conn) do %>
            <%= link "Account settings", to: Routes.page_path(@conn, :home) %>
            <%= link "Log out", to: Routes.session_path(@conn, :delete, TartuSmarterBike.Authentication.load_current_user(@conn)), method: "delete", id: "logout" %>
          <% else %>
            <%= link "Log in", to: Routes.session_path(@conn, :new) %>
            <%= link "Register", to: Routes.user_path(@conn, :new), id: "register_button" %>
          <% end %>
        </span>
      </nav>
    </header>
    <%= @inner_content %>
    <footer>
      <p>Tartu Smarter Bike © 2021</p>
    </footer>
  </body>
</html>